Repository cook4me/android, pull requests merged in 2023-05, with the labels that each got.

#192 Avoid raceCondition in AddProfileInfoTest
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/profile/EditProfileScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/signup/AddProfileInfoScreenTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/profile/ProfileViewModel.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/signUp/SignUpViewModel.kt
Labels: bug

#180 Feature/store profile image on firebase
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sdp/cook4me/repository/ProfileImageRepositoryTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/repository/ProfileRepositoryTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/form/DatePickerTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/form/InputFieldTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/form/IntegerSliderTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/form/TimePickerTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/form/ToggleSwitchTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/profile/EditProfileScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/profile/ProfileScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/profile/ProfileViewModelTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/signup/AddProfileInfoScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/signup/SignUpViewModelTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/application/ProfileService.kt
  app/src/main/java/ch/epfl/sdp/cook4me/application/ProfileServiceWithRepository.kt
  app/src/main/java/ch/epfl/sdp/cook4me/persistence/model/Profile.kt
  app/src/main/java/ch/epfl/sdp/cook4me/persistence/repository/ProfileImageRepository.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/common/form/TextFieldState.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/profile/EditProfileScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/profile/ProfileScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/profile/ProfileViewModel.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/signUp/AddProfileInfosScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/signUp/SignUpViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#162 Feature/Populate Map Firestore
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/detailedevent/DetailedEventScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/detailedevent/SetUpEvents.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/detailedevent/TestEvent.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/eventform/EventTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/map/MapPermissionWrapper.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/map/MapScreenTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/Cook4MeApp.kt
  app/src/main/java/ch/epfl/sdp/cook4me/application/EventFormService.kt
  app/src/main/java/ch/epfl/sdp/cook4me/persistence/repository/ObjectRepository.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/eventform/Event.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/map/MapPermissionWrapper.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/map/MapScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/map/MapViewModel.kt
Labels: enhancement

#231 Feature: challenge class
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sdp/cook4me/application/ChallengeFormServiceTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challenge/ChallengeFeedScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challengeform/ChallengeTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challengeform/CreateChallengeScreenTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/Cook4MeApp.kt
  app/src/main/java/ch/epfl/sdp/cook4me/application/ChallengeFormService.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/ChallengeFeedScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challengeform/Challenge.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challengeform/CreateChallengeScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/navigation/BottomNavigationBar.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/navigation/Cook4meNavHost.kt
  app/src/main/res/values/strings.xml
Labels: Destabilization Sprint

#235 Feature/Detailed Challenge Screen
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challengedetailed/ChallengeDetailedScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challengedetailed/ChallengeTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challengedetailed/CountdownTimerTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/detailedevent/DetailedEventScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/detailedevent/SetUpEvents.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/map/MapScreenTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challengedetailed/ChallengeDetailedScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challengedetailed/ChallengeDetailedViewModel.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challengedetailed/CountdownTimer.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Destabilization Sprint

#232 TupperwareInfos
  app/src/androidTest/java/ch/epfl/sdp/cook4me/repository/ProfileImageRepositoryTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/tupperwareswipe/TupperwareInfosTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/persistence/repository/ProfileImageRepository.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/profile/ProfileScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/profile/ProfileViewModel.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/tupperwareswipe/TupperwareInfos.kt
Labels: enhancement

#242 refactor challenge class
  app/src/androidTest/java/ch/epfl/sdp/cook4me/application/ChallengeFormServiceTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challengeform/ChallengeTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/application/ChallengeFormService.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challengeform/Challenge.kt
Labels: Destabilization Sprint

#237 Fix/delete profiles bug
  app/src/androidTest/java/ch/epfl/sdp/cook4me/repository/ProfileImageRepositoryTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/repository/ProfileRepositoryTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/signup/AddProfileInfoScreenTest.kt
Labels: bug

#245 Feature/user join challenge
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challengedetailed/ChallengeDetailedScreenTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challengedetailed/ChallengeDetailedScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challengedetailed/ChallengeDetailedViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Destabilization Sprint

#300 UI/Enlarge Map Forms
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challenge/form/CreateChallengeScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/event/form/CreateEventScreenTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/form/CreateChallengeScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/event/form/CreateEventScreen.kt
Labels: UI

#299 include logo
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/user/profile/EditProfileScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/user/profile/ProfileScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/user/profile/ProfileViewModelTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/user/signup/AddProfileInfoScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/user/signup/SignUpViewModelTest.kt
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v33/ic_launcher.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
Labels: UI

#288 Fix some offline mode issues
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/OfflineStatusIndicatorTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/tupperware/swipe/TupperwareSwipeScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/tupperwareswipe/TupperwareSwipeScreenTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/Cook4MeApp.kt
  app/src/main/java/ch/epfl/sdp/cook4me/application/RecipeFeedService.kt
  app/src/main/java/ch/epfl/sdp/cook4me/persistence/repository/FirebaseUtils.kt
  app/src/main/java/ch/epfl/sdp/cook4me/persistence/repository/RecipeNoteRepository.kt
  app/src/main/java/ch/epfl/sdp/cook4me/persistence/repository/RecipeRepository.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/common/OfflineStatusIndicator.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/navigation/BottomNavigationBar.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/navigation/Cook4meNavHost.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/tupperware/swipe/SwipeScreen.kt
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#282 Refactor/chat
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/chat/ChatTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/epfl/sdp/cook4me/Cook4MeApp.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/ChannelScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/ChatProfileActivity.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/ChatService.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/CoilImageLoaderFactory.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/ImageLoaderDecorator.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/chat/MessagesActivity.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/navigation/BottomNavigationBar.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/navigation/Cook4meNavHost.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/user/profile/ProfileViewModel.kt
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#304 Feature/beautify recipefeed
  app/src/androidTest/java/ch/epfl/sdp/cook4me/persistence/repository/RecipeRepositoryTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challenge/ChallengeFeedScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challenge/feed/ChallengeFeedTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challenge/feed/ChallengeItemTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challenge/feed/FilterScreenTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challenge/feed/SearchBarTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/challenge/feed/SearchViewModelTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/recipe/RecipeCreationScenarioTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/recipe/feed/RecipeDisplayTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/recipe/feed/RecipeFeedTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/recipe/feed/RecipeListScreenTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/application/RecipeFeedService.kt
  app/src/main/java/ch/epfl/sdp/cook4me/persistence/repository/ChallengeRepository.kt
  app/src/main/java/ch/epfl/sdp/cook4me/persistence/repository/RecipeRepository.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/ChallengeFeedScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/details/ChallengeDetailedScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/feed/ChallengeFeedScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/feed/ChallengeItem.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/feed/FilterScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/feed/SeachBar.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/feed/SearchViewModel.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/challenge/form/CreateChallengeScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/common/button/CreateNewItemButton.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/common/filters/Filters.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/navigation/BottomNavigationBar.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/navigation/Cook4meNavHost.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/recipe/CreateRecipeScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/recipe/feed/RecipeDisplay.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/recipe/feed/RecipeFeed.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/recipe/feed/RecipeListScreen.kt
  app/src/main/java/ch/epfl/sdp/cook4me/ui/recipe/feed/VoteIcon.kt
  app/src/main/res/values/strings.xml
Labels: UI

#312 Bug/navigate event
  app/build.gradle
  app/src/main/java/ch/epfl/sdp/cook4me/ui/navigation/Cook4meNavHost.kt
Labels: bug

#322 UI/beautify permission manager
  app/src/androidTest/java/ch/epfl/sdp/cook4me/permissions/PermissionManagerTest.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/map/MapPermissionWrapper.kt
  app/src/androidTest/java/ch/epfl/sdp/cook4me/ui/tupperware/form/CreateTupperwarePermissionWrapperTest.kt
  app/src/main/java/ch/epfl/sdp/cook4me/permissions/PermissionManager.kt
  app/src/main/java/ch/epfl/sdp/cook4me/permissions/PermissionRequesterScreen.kt
  app/src/main/res/values/strings.xml
Labels: UI
